import { readFileSync } from 'node:fs';
import path from 'node:path';
import { parse as parseToml, stringify } from 'smol-toml';
import * as v from 'valibot';
import type { WorkspaceDiscovery } from './discovery.ts';

/** Filename of the generated, fully-owned mise tasks include. */
export const miseTasksFileName = 'mise.tasks.toml';

/*
 * mise tasks run outside pnpm, so `node_modules/.bin` is not on PATH and a
 * bare `gtb` won't resolve the way it does in package.json scripts. Resolve
 * gtb per repo shape:
 *   - self-hosted: the `pnpm run gtb` script shim (source, no build needed)
 *   - depends on @gtbuchanan/CLI: `pnpm exec` finds it in node_modules
 *   - neither (hk-only adopter): bare `gtb` from mise's npm: backend, so no
 *     node_modules/pnpm project is needed — add npm:@gtbuchanan/CLI to [tools]
 */
const miseTaskPrefix = (
  discovery: Pick<WorkspaceDiscovery, 'dependsOnCli' | 'isSelfHosted'>,
): string => {
  if (discovery.isSelfHosted) {
    return 'pnpm run gtb';
  }

  return discovery.dependsOnCli ? 'pnpm exec gtb' : 'gtb';
};

const header = [
  '# Generated by `gtb sync` — do not edit.',
  `# Reference from mise.toml: [task_config] includes = ["${miseTasksFileName}"]`,
].join('\n');

/**
 * Generates the fully-owned `mise.tasks.toml` body. Uses the include-file
 * format (task name as the top-level table, no `[tasks]` prefix). sync
 * overwrites this wholesale, so it never round-trips the hand-authored
 * `mise.toml`.
 */
export const generateMiseTasks = (
  discovery: Pick<WorkspaceDiscovery, 'dependsOnCli' | 'isSelfHosted'>,
): string => {
  const gtb = miseTaskPrefix(discovery);
  const tasks = {
    'hk:all': {
      description: 'Run hk across all files (fixes locally, checks in CI)',
      run: `${gtb} hk all`,
    },
    'hk:base': {
      description: 'Run hk on files changed from a base ref (fixes locally, checks in CI)',
      run: `${gtb} hk base`,
    },
  };

  /*
   * Exactly one trailing newline so the generated file matches what hk's
   * end-of-file-fixer wants — otherwise the hook would rewrite it on every
   * commit and fight `gtb sync`.
   */
  return `${header}\n\n${stringify(tasks).trimEnd()}\n`;
};

const StringArray = v.array(v.string());

const TaskConfigSchema = v.looseObject({
  includes: v.optional(StringArray),
});

const MiseConfigSchema = v.looseObject({
  task_config: v.optional(TaskConfigSchema),
});

/**
 * Drift check for `gtb verify`: `gtb sync` writes `mise.tasks.toml`, but
 * the `[task_config] includes` line that loads it is a manual, one-time
 * edit (so sync never round-trips the comment-heavy `mise.toml`). Asserts
 * the include is present — read-only, so no comment-preservation risk.
 * Returns drift messages (empty when satisfied).
 */
export const checkMiseTasksInclude = (rootDir: string): readonly string[] => {
  const filePath = path.join(rootDir, 'mise.toml');
  let parsed: unknown;
  try {
    parsed = parseToml(readFileSync(filePath, 'utf8'));
  } catch {
    return ['mise.toml: invalid TOML'];
  }
  const result = v.safeParse(MiseConfigSchema, parsed);
  const includes = result.success ? result.output.task_config?.includes ?? [] : [];
  if (includes.includes(miseTasksFileName)) {
    return [];
  }

  return [
    `mise.toml: [task_config] includes must contain "${miseTasksFileName}" ` +
    '(run gtb sync, then add the include)',
  ];
};
