import path from 'node:path';
import {
  compileTs, coverageCodecovUpload, coverageVitestMerge, lintEslint,
  packNpm, prepare, testVitestE2e, testVitestFast,
  testVitestSlow, turboCheck, typecheckTs,
} from '../commands/leaf/index.ts';
import type { PackageCapabilities, WorkspaceDiscovery } from './discovery.ts';
import {
  Aggregate,
  type ConditionalEntry,
  type ToolFlags,
  collect,
  resolveToolFlags,
} from './turbo-config.ts';

const packageScriptEntries = (
  caps: PackageCapabilities,
  isSelfHosted: boolean,
): readonly ConditionalEntry<string>[] => {
  // Self-hosted repos define gtb as a package.json script (shim to source).
  // Bare `gtb` only resolves node_modules/.bin — not sibling scripts — so
  // Self-hosted must use `pnpm run gtb` to invoke the script by name.
  const cmd = (def: { readonly name: string }): string =>
    isSelfHosted ? `pnpm run gtb ${def.name}` : `gtb ${def.name}`;

  return [
    { condition: caps.hasTypeScript, key: typecheckTs.name, value: cmd(typecheckTs) },
    { condition: caps.isPublished, key: compileTs.name, value: cmd(compileTs) },
    { condition: caps.isPublished, key: packNpm.name, value: cmd(packNpm) },
    { condition: caps.hasEslint, key: lintEslint.name, value: cmd(lintEslint) },
    {
      condition: caps.hasVitestTests,
      key: testVitestFast.name,
      value: cmd(testVitestFast),
    },
    {
      condition: caps.hasVitestTests,
      key: testVitestSlow.name,
      value: cmd(testVitestSlow),
    },
    {
      condition: caps.hasVitestE2e,
      key: testVitestE2e.name,
      value: cmd(testVitestE2e),
    },
    {
      condition: caps.hasVitestTests,
      key: coverageCodecovUpload.name,
      value: cmd(coverageCodecovUpload),
    },
    {
      condition: caps.hasVitestTests,
      key: coverageVitestMerge.name,
      value: cmd(coverageVitestMerge),
    },
  ];
};

/** Generates the gtb shim script for self-hosted packages. */
const gtbShim = (pkgDir: string, rootDir: string): string => {
  const rel = path.relative(pkgDir, rootDir).replaceAll('\\', '/');

  return `node --experimental-strip-types ${rel}/packages/cli/bin/gtb.ts`;
};

/** Generates per-package scripts from capabilities. */
export const generatePackageScripts = (
  caps: PackageCapabilities,
  isSelfHosted: boolean,
  rootDir?: string,
): Record<string, string> => {
  const scripts = collect(packageScriptEntries(caps, isSelfHosted));
  if (isSelfHosted && rootDir !== undefined) {
    scripts['gtb'] = gtbShim(caps.dir, rootDir);
  }

  return scripts;
};

/** Required root scripts — validated by turbo:check. */
const requiredRootScripts = (isSelfHosted: boolean): Readonly<Record<string, string>> => {
  const prefix = isSelfHosted ? 'pnpm run gtb' : 'gtb';
  return {
    [prepare.name]: `${prefix} ${prepare.name}`,
    [turboCheck.name]: `${prefix} ${turboCheck.name}`,
  };
};

/** Optional turbo alias scripts — generated by turbo:init, not validated. */
const aliasRootScriptEntries = (flags: ToolFlags): readonly ConditionalEntry<string>[] => [
  { condition: flags.hasCheck, key: Aggregate.check, value: `turbo run ${Aggregate.check}` },
  {
    condition: flags.hasCheck || flags.hasPublished,
    key: Aggregate.buildCi,
    value: `turbo run ${Aggregate.buildCi}`,
  },
  {
    condition: flags.hasCheck || flags.hasPublished || flags.hasE2e,
    key: Aggregate.build,
    value: `turbo run ${Aggregate.build}`,
  },
  {
    condition: flags.hasVitest,
    key: Aggregate.coverageMerge,
    value: `turbo run ${Aggregate.coverageMerge}`,
  },
  {
    condition: flags.hasPublished,
    key: Aggregate.pack,
    value: `turbo run ${Aggregate.pack}`,
  },
  { condition: flags.hasE2e, key: Aggregate.testE2e, value: `turbo run ${Aggregate.testE2e}` },
  { condition: flags.hasVitest, key: Aggregate.testSlow, value: `turbo run ${Aggregate.testSlow}` },
];

/** Generates all root-level scripts (required + optional aliases). */
export const generateRootScripts = (
  discovery: WorkspaceDiscovery,
): Record<string, string> => ({
  ...collect(aliasRootScriptEntries(resolveToolFlags(discovery))),
  ...requiredRootScripts(discovery.isSelfHosted),
});

/** Generates only required root scripts for drift validation. */
export const generateRequiredRootScripts = (
  discovery: WorkspaceDiscovery,
): Record<string, string> => ({ ...requiredRootScripts(discovery.isSelfHosted) });
